app:
  title: "Music Player"
  icon: "fa5s.music"
  icon_path: "music_player/resources/play.png"
  window:
    width: 1200
    height: 800
    min_width: 800
    min_height: 600

logging:
  level: "DEBUG" # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: True # Log messages to [app_title].log
  log_to_console: True # Print log messages to the terminal/console
  clear_on_startup: True # Clear the log file each time the app starts

sidebar:
  title: "Music Player"
  icon: "fa5s.music"
  sections:
    - title: "Main"
      items:
        - id: "dashboard"
          title: "Dashboard"
          icon: "fa5s.home"
          page: "DashboardPage"
        - id: "player"
          title: "Player"
          icon: "fa5s.play"
          page: "PlayerPage"
        - id: "playlists"
          title: "Playlists"
          icon: "fa5s.list"
          page: "PlaylistsPage"
        - id: "browser"
          title: "Browser"
          icon: "fa5s.folder-open"
          page: "BrowserPage"
    - title: "Settings"
      items:
        - id: "preferences"
          title: "Preferences"
          icon: "fa5s.cog"
          page: "PreferencesPage"

# AI Configuration Section
ai:
  groq:
    # Max requests per minute allowed by Groq (free tier is 30)
    # We set slightly lower to be safe.
    requests_per_minute: 28
    # Number of filenames to send in each API call
    batch_size: 30
    # Groq model to use for classification
    model_name: "llama-3.3-70b-versatile" # Example: Use 70b for potentially higher accuracy, 8b for speed
